name: RAX3000Me
on:
  push:
    branches:
      - main
    paths:
      - 'RAX3000Me/packages.txt'
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

env:
  SDK_URL: https://downloads.immortalwrt.org/releases/24.10-SNAPSHOT/targets/mediatek/filogic/immortalwrt-sdk-24.10-SNAPSHOT-mediatek-filogic_gcc-13.3.0_musl.Linux-x86_64.tar.zst
  DOWNLOAD_URL: https://downloads.immortalwrt.org/releases/24.10-SNAPSHOT/targets/mediatek/filogic/immortalwrt-imagebuilder-24.10-SNAPSHOT-mediatek-filogic.Linux-x86_64.tar.zst
  PROFILE: cmcc_rax3000me
  FILES_FOLDER: RAX3000Me/files
  UCI_CUSTOM_FILE: RAX3000Me/uci-custom
  PACKAGES_LIST: RAX3000Me/packages.txt
  DIY_SH: RAX3000Me/diy.sh
  UPLOAD_FIRMWARE: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: æ£€æŸ¥é¡¹ç›®åˆ†æ”¯
      uses: actions/checkout@main

    - name: åˆå§‹åŒ–ç¼–è¯‘ç¯å¢ƒ
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt update
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo apt autoremove --purge
        sudo apt clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        echo "FIRMWARE_VERSION=$(date +"%y%m%d")" >> $GITHUB_ENV
        echo "START_DATE=$(date +%s)" >> $GITHUB_ENV

    - name: ä¸‹è½½ OpenWrt SDK
      working-directory: /workdir
      run: |
        df -hT $PWD
        # ä¸‹è½½ openwrt_sdk
        wget -O openwrt_sdk.tar.zst $SDK_URL
        mkdir -p openwrt_sdk
        tar -C openwrt_sdk -xvf openwrt_sdk.tar.zst --strip-components 1
        ln -sf /workdir/openwrt_sdk $GITHUB_WORKSPACE/openwrt_sdk

    - name: åŠ è½½ OpenWrt SDK è½¯ä»¶æº
      run: |
        chmod +x $DIY_SH
        cd openwrt_sdk
        $GITHUB_WORKSPACE/$DIY_SH

    - name: æ›´æ–°å¹¶ä¸‹è½½ OpenWrt SDK è½¯ä»¶æº
      run: |
        cd openwrt_sdk
        ./scripts/feeds update -a && ./scripts/feeds install -a
        make defconfig

    - name: å¼€å§‹ç¼–è¯‘ PACKAGE
      id: compile_package
      run: |
        cd openwrt_sdk
        # ç¼–è¯‘è½¯ä»¶
        while IFS= read -r package; do
            [[ -z "$package" ]] && continue
            if [[ "$package" != "#"* ]]; then
                echo "æ­£åœ¨ç¼–è¯‘: $package"
                make "package/$package/compile" -j$(nproc) || make "package/$package/compile" -j1 V=s
            fi
        done < "packages_compile"
        mkdir -p packages
        # ç¼–è¯‘å®Œæˆåï¼Œå°†ç¼–è¯‘å¥½çš„è½¯ä»¶åŒ…å¤åˆ¶åˆ° packages æ–‡ä»¶å¤¹
        while read line; do
          path=$(find bin/packages/*/base -type f -name "$line*")
          echo $path
          # cp $path packages
          find ./bin/packages/*/base -type f -name "${line}*" -exec cp -t ./packages {} +
        done < packages_list
        
    - name: ä¸‹è½½ Image Builder
      working-directory: /workdir
      run: |
        df -hT $PWD
        wget -O image_builder.tar.zst $DOWNLOAD_URL
        mkdir -p image_builder
        tar -C image_builder -xvf image_builder.tar.zst --strip-components 1
        ln -sf /workdir/image_builder $GITHUB_WORKSPACE/image_builder

    - name: åŠ è½½è‡ªå®šä¹‰é…ç½®ä»¥åŠä¸‰æ–¹è½¯ä»¶åŒ…
      run: |
        [ -e $FILES_FOLDER ] && mv $FILES_FOLDER image_builder/files
        [ -e $PACKAGES_LIST ] && mv $PACKAGES_LIST image_builder/packages.txt
        # æ–°å»ºæ–‡ä»¶å¤¹
        mkdir -p image_builder/packages
        # å¤åˆ¶IPKåŒ…
        cp openwrt_sdk/packages/*.ipk image_builder/packages
        rm -rf openwrt_sdk/*

    - name: ç¼–è¯‘å›ºä»¶
      id: compile
      run: |
        cd image_builder
        PACKAGES=$(cat packages.txt | tr '\n' ' ')
        make image PROFILE="$PROFILE" PACKAGES="$PACKAGES" FILES="files"
        echo "status=success" >> $GITHUB_OUTPUT
    
    - name: æ•´ç†æ–‡ä»¶
      id: organize
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        # æ•´ç†å›ºä»¶åŒ…æ—¶å€™,åˆ é™¤æ‚¨ä¸æƒ³è¦çš„å›ºä»¶æˆ–è€…æ–‡ä»¶,è®©å®ƒä¸éœ€è¦ä¸Šä¼ åˆ°Actionsç©ºé—´
        cd image_builder/bin/targets/*/*
        rm -rf sha256sums
        rm -rf *.manifest
        rm -rf *.json
        mv *sysupgrade.itb RAX3000Me-${FIRMWARE_VERSION}-squashfs-sysupgrade.itb
        for f in *cmcc_rax3000me*; do mv -- "$f" "cmcc_rax3000me-${f#*cmcc_rax3000me-}"; done
        echo -e "$(sha256sum *)\n" > sha256sums
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: åˆ é™¤æ—§çš„Release
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: RAX3000Me
      run: |
        RELEASE_URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG_NAME"
        RELEASE_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $RELEASE_URL | jq -r '.id')
        if [ "$RELEASE_ID" != "null" ]; then
          echo "ğŸ—‘ï¸ åˆ é™¤Releaseä¸­: $RELEASE_ID..."
          curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID"
          echo "âœ… Releaseåˆ é™¤æˆåŠŸ!"
        else
          echo "âš ï¸ æœªæ‰¾åˆ°tagçš„Release: $TAG_NAME"
        fi

    - name: åˆ›å»ºreleaseæ ‡ç­¾
      id: tag
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "ç¼–è¯‘æ—¶é—´ï¼š$(date -d "@${{ env.START_DATE }}" +"%Yå¹´%mæœˆ%dæ—¥ %Hç‚¹%Måˆ†")" >> release.txt
        echo "é»˜è®¤ç½‘å…³ï¼š192.168.5.1" >> release.txt
        echo åŒ…å«æ’ä»¶ï¼š$(grep "luci-app-\(.*\)" image_builder/packages.txt | sed "s/luci-app-\(.*\)/\1/g" | tr '\n' ' ') >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT
  
    - name: å°†å›ºä»¶ä¸Šä¼ åˆ°release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: upload-release
      with:
        name: RAX3000Me-${{ env.FIRMWARE_VERSION }}
        tag_name: RAX3000Me
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
  
    - name: Telegram é€šçŸ¥
      if: always() && !cancelled()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHATID: ${{ secrets.TELEGRAM_CHATID }}
      run: |
        duration=$((($(date +%s)-${{ env.START_DATE }})/60)) && time=$((duration/60))å°æ—¶$((duration%60))åˆ†é’Ÿ
        if [ "${{ steps.compile.outputs.status }}" == 'success' ]; then
          content="ğŸ‰RAX3000Meå›ºä»¶ç¼–è¯‘æˆåŠŸğŸ‰%0Aå›ºä»¶ç‰ˆæœ¬ï¼š${{ env.FIRMWARE_VERSION }}%0Aç¼–è¯‘ç”¨æ—¶ï¼š${time}"
        else
          content="âŒRAX3000Meå›ºä»¶ç¼–è¯‘å¤±è´¥âŒ%0Aå›ºä»¶ç‰ˆæœ¬ï¼š${{ env.FIRMWARE_VERSION }}%0Aç¼–è¯‘ç”¨æ—¶ï¼š${time}"
        fi
        curl "https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ env.TELEGRAM_CHATID }}&text=${content}"
